### ISSUE TITLE
Alternative Implementation

### ISSUE THREAD

**Issue by eorroe** [ctruett/FeaturePresentation#1]
I like the idea. Yet wouldn't it be better if you can some how create a new tab with the selected part of the code which is somehow connected to the tab that the code was extracted from. Like the default: **File: New View into File**

This would eliminate:

Deleting the _square with 3 dots_ that represent the folded code. Just in case you accidentally save the file and close or something like that happens. Plus indentation can get annoying.

I understand if you just through this together (but just a thought). Also sounds challenging to do.

Thanks

**Comment by ctruett** [comment]
Thanks for the feedback!

The _square with three dots_ that you are seeing is actually just a symbol that Sublime Text uses when it has hidden a section of code away within a fold. Nothing is lost or overwritten, just neatly tucked away until you decide to unfold it. So even if you saved the document while in 'isolation mode', you would not have accidentally lost what you were working on.

**Comment by eorroe** [comment]
I know I mentioned that:

> Deleting the _square with 3 dots_ that represent the folded code

I'm saying if you press backspace on it. It would delete your folded code.

So what happens if you did that without even realizing, and then happen to save and close. Or your computer restarts on you. Since sublime saves the last state, but not the undos you won't be able to recover your code.

**Comment by ctruett** [comment]
Oh, I misunderstood. I will consider your suggestions.

**Comment by eorroe** [comment]
Ok thanks

**Comment by ctruett** [comment]
Just wanted to let you know that the newest release of Feature Presentation works like you wanted in your original issue posting. Let me know if you have any other suggestions / issues!

**Comment by eorroe** [comment]
Thank You!!! This is awesome. Only one little glitch I see is the folded block gets moved to the next line in the original file. Meaning If I highlight a certain part which has folded code then press F8. Even without editing the code when I close the isolated tab and go back to the original the fold block gets moved to the next line.

Try different combinations of the following:

Bold part will be folded (replaced by a fold block)

test = {**"hello"**}

highlight the line, close the isolated tab and look at the original file folded code.

I don't have a screen recorder, to really show you so hopefully you can figure it out? 

Thanks.

**Comment by ctruett** [comment]
Hmm, I have tried several times to duplicate this, but have so far been unable to. The folds unfold automatically when I return to the original view.

Try using [**Screenmailer**](https://www.screenmailer.com) or [**Screencast-O-Matic**](http://www.screencast-o-matic.com) and see if you can get a recording of this behavior.

**Comment by eorroe** [comment]
Ok I made the recording it's a `mp4` file so [here](https://drive.google.com/file/d/0B9Fa6BiJ8On3dWhMR3haVmhXc1k/view?usp=sharing) I put it on Google Drive.

**Comment by ctruett** [comment]
Thanks for the video. It is working as expected now. Either do a `git pull` from the package folder or wait for it to hit Package Control (an hour or two) and let me know if you have any issues.

**Comment by ctruett** [comment]
Actually, scratch that. The fixes I implemented broke some other things. I'll get back to you once I have a better solution.

**Comment by kovla** [comment]
Personally I liked the previous version better. Saving the temporary edit space there used to save the entire document, whereas with the new implementation a save dialog opens, which is not useful. Not a huge issue, and I guess I can always git pull the old version, so just a tip.

**Comment by ctruett** [comment]
Do a fresh pull on the repo, and add

```
“fp_basic”: true
```

to your user preferences to restore the old behavior.

**Comment by kovla** [comment]
Excellent, thanks! A very customized approach to your users, much appreciated :)

**Comment by ctruett** [comment]
@eorroe The bug you found should be squashed now. Pull a fresh copy down and let me know if it is working as expected on your end.

**Comment by eorroe** [comment]
@ctruett Dude I totally forgot about this, and unistalled the plugin till you fixed, it didn't see your message, but yea I needed to do something like this, and awesome thanks again
