### ISSUE TITLE
Possible to remove fold boxes? 

### ISSUE THREAD

**Issue by kovla** [ctruett/FeaturePresentation#2]
Hi,

First of all, I would like to thank you for making this plugin. I use ST3 for text writing, and this feature really helps to focus on a passage one is currently working on. 

Not a big issue, but perhaps something that can be improved: when the outside text folds, two small boxes appear on top and at the bottom of the current text screen. With my Monokai theme, these are bright yellow on the black background. This unfortunate combination attracts attention, which sort of defies the original purpose of focusing on a piece of text. I was wondering if it is possible to remove these boxes? Or is it better to try and look into changing the box color to something more suitable? 

Thank you in advance for your reaction. 

Kind regards,
Maxim

**Comment by ctruett** [comment]
Hey!

Thanks for the feedback :) 

Unfortunately, the fold graphic is part of the ST3 UI theme, and is controlled by a `fold.png` in the main theme directory. I have looked into other ways to solve this issue, such as changing the opacity of all text except the selected region, but unfortunately there is no way to change this programmatically with the current limited API.

You may try changing the `fold.png`, per this thread: https://www.sublimetext.com/forum/viewtopic.php?f=3&t=16262

In the mean time, I will be researching ways to achieve the same functionality with less distractions, and I will update the existing repo and forum thread should I find a better way of doing things.

Do you have any other suggestions or questions? I would love to hear them!

**Comment by kovla** [comment]
That is actually an acceptable solution. I just edited the PNG file, replaced yellow by grey and added some transparency. Now it is very much in line with the Monokai theme. Thanks very much indeed!
