### ISSUE TITLE
Non-plugin owned scratch buffer content pulled in

### ISSUE THREAD

**Issue by nikcorg** [ctruett/FeaturePresentation#5]
This is a super useful plugin. I just love it! I love it so much, I've found a bug in it :-)

After you've invoked the plugin once, any content from a scratch buffer (not sure that's the correct term) is pulled in into the active buffer or the leftmost buffer at the cursor. In my case, this is usually a git diff entry from viewing the git log.

Steps to repeat:

1. open file
2. edit part of file in Feature Presentation mode
3. close scratch buffer
4. view entry in e.g. git log
5. close entry
6. observe scratch buffer content inserted

I made a recording to demonstrate:

![presentation](https://cloud.githubusercontent.com/assets/816988/23220833/1f015f92-f91b-11e6-8a79-3d9bcbc24f17.gif)

**Comment by nikcorg** [comment]
Just a small bump, to check whether @ctruett is still tuned in or not. Sorry for the annoyance.

**Comment by ctruett** [comment]
This appears to be resolved with the changes I've just pulled in from another contributor. Sorry it has taken so long!
